# Generated by Django 6.0.2 on 2026-02-27

from django.db import migrations


def seed_default_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    default_roles = [
        ('BACKER', 'Backer role for funding projects'),
        ('CREATOR', 'Creator role for launching projects'),
        ('ADMIN', 'Admin role for internal platform operations'),
    ]

    for role_name, description in default_roles:
        Role.objects.get_or_create(name=role_name, defaults={'description': description})


def unseed_default_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Role.objects.filter(name__in=['BACKER', 'CREATOR', 'ADMIN']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_userrole'),
    ]

    operations = [
        migrations.RunPython(seed_default_roles, unseed_default_roles),
    ]
