# Generated by Django 6.0.2 on 2026-03-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorchannel',
            name='channel_handle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='sync_error',
            field=models.TextField(blank=True),
        ),
    ]
