# Generated by Django 6.0.2 on 2026-03-06 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_creatorchannel_channel_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorchannel',
            name='channel_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='onboarding_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='onboarding_status',
            field=models.CharField(choices=[('started', 'Started'), ('channel_connected', 'Channel Connected'), ('complete', 'Complete')], default='started', max_length=24),
        ),
    ]
