# Generated by Django 6.0.2 on 2026-03-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_creatorchannel_channel_connected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorchannel',
            name='youtube_channel_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
